// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: internal/data.proto

package internal

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type WriteShardRequest struct {
	ShardID              *uint64  `protobuf:"varint,1,req,name=ShardID" json:"ShardID,omitempty"`
	Points               [][]byte `protobuf:"bytes,2,rep,name=Points" json:"Points,omitempty"`
	Database             *string  `protobuf:"bytes,3,opt,name=Database" json:"Database,omitempty"`
	RetentionPolicy      *string  `protobuf:"bytes,4,opt,name=RetentionPolicy" json:"RetentionPolicy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteShardRequest) Reset()         { *m = WriteShardRequest{} }
func (m *WriteShardRequest) String() string { return proto.CompactTextString(m) }
func (*WriteShardRequest) ProtoMessage()    {}
func (*WriteShardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7438786364df21e1, []int{0}
}
func (m *WriteShardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteShardRequest.Unmarshal(m, b)
}
func (m *WriteShardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteShardRequest.Marshal(b, m, deterministic)
}
func (m *WriteShardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteShardRequest.Merge(m, src)
}
func (m *WriteShardRequest) XXX_Size() int {
	return xxx_messageInfo_WriteShardRequest.Size(m)
}
func (m *WriteShardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteShardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WriteShardRequest proto.InternalMessageInfo

func (m *WriteShardRequest) GetShardID() uint64 {
	if m != nil && m.ShardID != nil {
		return *m.ShardID
	}
	return 0
}

func (m *WriteShardRequest) GetPoints() [][]byte {
	if m != nil {
		return m.Points
	}
	return nil
}

func (m *WriteShardRequest) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

func (m *WriteShardRequest) GetRetentionPolicy() string {
	if m != nil && m.RetentionPolicy != nil {
		return *m.RetentionPolicy
	}
	return ""
}

type WriteShardResponse struct {
	Code                 *int32   `protobuf:"varint,1,req,name=Code" json:"Code,omitempty"`
	Message              *string  `protobuf:"bytes,2,opt,name=Message" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteShardResponse) Reset()         { *m = WriteShardResponse{} }
func (m *WriteShardResponse) String() string { return proto.CompactTextString(m) }
func (*WriteShardResponse) ProtoMessage()    {}
func (*WriteShardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7438786364df21e1, []int{1}
}
func (m *WriteShardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteShardResponse.Unmarshal(m, b)
}
func (m *WriteShardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteShardResponse.Marshal(b, m, deterministic)
}
func (m *WriteShardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteShardResponse.Merge(m, src)
}
func (m *WriteShardResponse) XXX_Size() int {
	return xxx_messageInfo_WriteShardResponse.Size(m)
}
func (m *WriteShardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteShardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WriteShardResponse proto.InternalMessageInfo

func (m *WriteShardResponse) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *WriteShardResponse) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type ExecuteStatementRequest struct {
	Statement            *string  `protobuf:"bytes,1,req,name=Statement" json:"Statement,omitempty"`
	Database             *string  `protobuf:"bytes,2,req,name=Database" json:"Database,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteStatementRequest) Reset()         { *m = ExecuteStatementRequest{} }
func (m *ExecuteStatementRequest) String() string { return proto.CompactTextString(m) }
func (*ExecuteStatementRequest) ProtoMessage()    {}
func (*ExecuteStatementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7438786364df21e1, []int{2}
}
func (m *ExecuteStatementRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteStatementRequest.Unmarshal(m, b)
}
func (m *ExecuteStatementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteStatementRequest.Marshal(b, m, deterministic)
}
func (m *ExecuteStatementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteStatementRequest.Merge(m, src)
}
func (m *ExecuteStatementRequest) XXX_Size() int {
	return xxx_messageInfo_ExecuteStatementRequest.Size(m)
}
func (m *ExecuteStatementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteStatementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteStatementRequest proto.InternalMessageInfo

func (m *ExecuteStatementRequest) GetStatement() string {
	if m != nil && m.Statement != nil {
		return *m.Statement
	}
	return ""
}

func (m *ExecuteStatementRequest) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

type ExecuteStatementResponse struct {
	Code                 *int32   `protobuf:"varint,1,req,name=Code" json:"Code,omitempty"`
	Message              *string  `protobuf:"bytes,2,opt,name=Message" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteStatementResponse) Reset()         { *m = ExecuteStatementResponse{} }
func (m *ExecuteStatementResponse) String() string { return proto.CompactTextString(m) }
func (*ExecuteStatementResponse) ProtoMessage()    {}
func (*ExecuteStatementResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7438786364df21e1, []int{3}
}
func (m *ExecuteStatementResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteStatementResponse.Unmarshal(m, b)
}
func (m *ExecuteStatementResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteStatementResponse.Marshal(b, m, deterministic)
}
func (m *ExecuteStatementResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteStatementResponse.Merge(m, src)
}
func (m *ExecuteStatementResponse) XXX_Size() int {
	return xxx_messageInfo_ExecuteStatementResponse.Size(m)
}
func (m *ExecuteStatementResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteStatementResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteStatementResponse proto.InternalMessageInfo

func (m *ExecuteStatementResponse) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *ExecuteStatementResponse) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type CreateIteratorRequest struct {
	ShardIDs             []uint64 `protobuf:"varint,1,rep,name=ShardIDs" json:"ShardIDs,omitempty"`
	Measurement          []byte   `protobuf:"bytes,2,req,name=Measurement" json:"Measurement,omitempty"`
	Opt                  []byte   `protobuf:"bytes,3,req,name=Opt" json:"Opt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateIteratorRequest) Reset()         { *m = CreateIteratorRequest{} }
func (m *CreateIteratorRequest) String() string { return proto.CompactTextString(m) }
func (*CreateIteratorRequest) ProtoMessage()    {}
func (*CreateIteratorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7438786364df21e1, []int{4}
}
func (m *CreateIteratorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateIteratorRequest.Unmarshal(m, b)
}
func (m *CreateIteratorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateIteratorRequest.Marshal(b, m, deterministic)
}
func (m *CreateIteratorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateIteratorRequest.Merge(m, src)
}
func (m *CreateIteratorRequest) XXX_Size() int {
	return xxx_messageInfo_CreateIteratorRequest.Size(m)
}
func (m *CreateIteratorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateIteratorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateIteratorRequest proto.InternalMessageInfo

func (m *CreateIteratorRequest) GetShardIDs() []uint64 {
	if m != nil {
		return m.ShardIDs
	}
	return nil
}

func (m *CreateIteratorRequest) GetMeasurement() []byte {
	if m != nil {
		return m.Measurement
	}
	return nil
}

func (m *CreateIteratorRequest) GetOpt() []byte {
	if m != nil {
		return m.Opt
	}
	return nil
}

type CreateIteratorResponse struct {
	Err                  *string        `protobuf:"bytes,1,opt,name=Err" json:"Err,omitempty"`
	Type                 *int32         `protobuf:"varint,2,req,name=Type" json:"Type,omitempty"`
	Stats                *IteratorStats `protobuf:"bytes,3,opt,name=Stats" json:"Stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateIteratorResponse) Reset()         { *m = CreateIteratorResponse{} }
func (m *CreateIteratorResponse) String() string { return proto.CompactTextString(m) }
func (*CreateIteratorResponse) ProtoMessage()    {}
func (*CreateIteratorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7438786364df21e1, []int{5}
}
func (m *CreateIteratorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateIteratorResponse.Unmarshal(m, b)
}
func (m *CreateIteratorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateIteratorResponse.Marshal(b, m, deterministic)
}
func (m *CreateIteratorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateIteratorResponse.Merge(m, src)
}
func (m *CreateIteratorResponse) XXX_Size() int {
	return xxx_messageInfo_CreateIteratorResponse.Size(m)
}
func (m *CreateIteratorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateIteratorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateIteratorResponse proto.InternalMessageInfo

func (m *CreateIteratorResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

func (m *CreateIteratorResponse) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *CreateIteratorResponse) GetStats() *IteratorStats {
	if m != nil {
		return m.Stats
	}
	return nil
}

type IteratorStats struct {
	SeriesN              *int64   `protobuf:"varint,1,opt,name=SeriesN" json:"SeriesN,omitempty"`
	PointN               *int64   `protobuf:"varint,2,opt,name=PointN" json:"PointN,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IteratorStats) Reset()         { *m = IteratorStats{} }
func (m *IteratorStats) String() string { return proto.CompactTextString(m) }
func (*IteratorStats) ProtoMessage()    {}
func (*IteratorStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_7438786364df21e1, []int{6}
}
func (m *IteratorStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IteratorStats.Unmarshal(m, b)
}
func (m *IteratorStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IteratorStats.Marshal(b, m, deterministic)
}
func (m *IteratorStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IteratorStats.Merge(m, src)
}
func (m *IteratorStats) XXX_Size() int {
	return xxx_messageInfo_IteratorStats.Size(m)
}
func (m *IteratorStats) XXX_DiscardUnknown() {
	xxx_messageInfo_IteratorStats.DiscardUnknown(m)
}

var xxx_messageInfo_IteratorStats proto.InternalMessageInfo

func (m *IteratorStats) GetSeriesN() int64 {
	if m != nil && m.SeriesN != nil {
		return *m.SeriesN
	}
	return 0
}

func (m *IteratorStats) GetPointN() int64 {
	if m != nil && m.PointN != nil {
		return *m.PointN
	}
	return 0
}

type IteratorCostRequest struct {
	ShardIDs             []uint64 `protobuf:"varint,1,rep,name=ShardIDs" json:"ShardIDs,omitempty"`
	Measurement          []byte   `protobuf:"bytes,2,req,name=Measurement" json:"Measurement,omitempty"`
	Opt                  []byte   `protobuf:"bytes,3,req,name=Opt" json:"Opt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IteratorCostRequest) Reset()         { *m = IteratorCostRequest{} }
func (m *IteratorCostRequest) String() string { return proto.CompactTextString(m) }
func (*IteratorCostRequest) ProtoMessage()    {}
func (*IteratorCostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7438786364df21e1, []int{7}
}
func (m *IteratorCostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IteratorCostRequest.Unmarshal(m, b)
}
func (m *IteratorCostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IteratorCostRequest.Marshal(b, m, deterministic)
}
func (m *IteratorCostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IteratorCostRequest.Merge(m, src)
}
func (m *IteratorCostRequest) XXX_Size() int {
	return xxx_messageInfo_IteratorCostRequest.Size(m)
}
func (m *IteratorCostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IteratorCostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IteratorCostRequest proto.InternalMessageInfo

func (m *IteratorCostRequest) GetShardIDs() []uint64 {
	if m != nil {
		return m.ShardIDs
	}
	return nil
}

func (m *IteratorCostRequest) GetMeasurement() []byte {
	if m != nil {
		return m.Measurement
	}
	return nil
}

func (m *IteratorCostRequest) GetOpt() []byte {
	if m != nil {
		return m.Opt
	}
	return nil
}

type IteratorCostResponse struct {
	Err                  *string       `protobuf:"bytes,1,opt,name=Err" json:"Err,omitempty"`
	Cost                 *IteratorCost `protobuf:"bytes,2,opt,name=Cost" json:"Cost,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *IteratorCostResponse) Reset()         { *m = IteratorCostResponse{} }
func (m *IteratorCostResponse) String() string { return proto.CompactTextString(m) }
func (*IteratorCostResponse) ProtoMessage()    {}
func (*IteratorCostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7438786364df21e1, []int{8}
}
func (m *IteratorCostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IteratorCostResponse.Unmarshal(m, b)
}
func (m *IteratorCostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IteratorCostResponse.Marshal(b, m, deterministic)
}
func (m *IteratorCostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IteratorCostResponse.Merge(m, src)
}
func (m *IteratorCostResponse) XXX_Size() int {
	return xxx_messageInfo_IteratorCostResponse.Size(m)
}
func (m *IteratorCostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IteratorCostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IteratorCostResponse proto.InternalMessageInfo

func (m *IteratorCostResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

func (m *IteratorCostResponse) GetCost() *IteratorCost {
	if m != nil {
		return m.Cost
	}
	return nil
}

type IteratorCost struct {
	NumShards            *int64   `protobuf:"varint,1,opt,name=NumShards" json:"NumShards,omitempty"`
	NumSeries            *int64   `protobuf:"varint,2,opt,name=NumSeries" json:"NumSeries,omitempty"`
	CachedValues         *int64   `protobuf:"varint,3,opt,name=CachedValues" json:"CachedValues,omitempty"`
	NumFiles             *int64   `protobuf:"varint,4,opt,name=NumFiles" json:"NumFiles,omitempty"`
	BlocksRead           *int64   `protobuf:"varint,5,opt,name=BlocksRead" json:"BlocksRead,omitempty"`
	BlockSize            *int64   `protobuf:"varint,6,opt,name=BlockSize" json:"BlockSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IteratorCost) Reset()         { *m = IteratorCost{} }
func (m *IteratorCost) String() string { return proto.CompactTextString(m) }
func (*IteratorCost) ProtoMessage()    {}
func (*IteratorCost) Descriptor() ([]byte, []int) {
	return fileDescriptor_7438786364df21e1, []int{9}
}
func (m *IteratorCost) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IteratorCost.Unmarshal(m, b)
}
func (m *IteratorCost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IteratorCost.Marshal(b, m, deterministic)
}
func (m *IteratorCost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IteratorCost.Merge(m, src)
}
func (m *IteratorCost) XXX_Size() int {
	return xxx_messageInfo_IteratorCost.Size(m)
}
func (m *IteratorCost) XXX_DiscardUnknown() {
	xxx_messageInfo_IteratorCost.DiscardUnknown(m)
}

var xxx_messageInfo_IteratorCost proto.InternalMessageInfo

func (m *IteratorCost) GetNumShards() int64 {
	if m != nil && m.NumShards != nil {
		return *m.NumShards
	}
	return 0
}

func (m *IteratorCost) GetNumSeries() int64 {
	if m != nil && m.NumSeries != nil {
		return *m.NumSeries
	}
	return 0
}

func (m *IteratorCost) GetCachedValues() int64 {
	if m != nil && m.CachedValues != nil {
		return *m.CachedValues
	}
	return 0
}

func (m *IteratorCost) GetNumFiles() int64 {
	if m != nil && m.NumFiles != nil {
		return *m.NumFiles
	}
	return 0
}

func (m *IteratorCost) GetBlocksRead() int64 {
	if m != nil && m.BlocksRead != nil {
		return *m.BlocksRead
	}
	return 0
}

func (m *IteratorCost) GetBlockSize() int64 {
	if m != nil && m.BlockSize != nil {
		return *m.BlockSize
	}
	return 0
}

type FieldDimensionsRequest struct {
	ShardIDs             []uint64 `protobuf:"varint,1,rep,name=ShardIDs" json:"ShardIDs,omitempty"`
	Measurement          []byte   `protobuf:"bytes,2,req,name=Measurement" json:"Measurement,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FieldDimensionsRequest) Reset()         { *m = FieldDimensionsRequest{} }
func (m *FieldDimensionsRequest) String() string { return proto.CompactTextString(m) }
func (*FieldDimensionsRequest) ProtoMessage()    {}
func (*FieldDimensionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7438786364df21e1, []int{10}
}
func (m *FieldDimensionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldDimensionsRequest.Unmarshal(m, b)
}
func (m *FieldDimensionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldDimensionsRequest.Marshal(b, m, deterministic)
}
func (m *FieldDimensionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldDimensionsRequest.Merge(m, src)
}
func (m *FieldDimensionsRequest) XXX_Size() int {
	return xxx_messageInfo_FieldDimensionsRequest.Size(m)
}
func (m *FieldDimensionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldDimensionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FieldDimensionsRequest proto.InternalMessageInfo

func (m *FieldDimensionsRequest) GetShardIDs() []uint64 {
	if m != nil {
		return m.ShardIDs
	}
	return nil
}

func (m *FieldDimensionsRequest) GetMeasurement() []byte {
	if m != nil {
		return m.Measurement
	}
	return nil
}

type FieldDimensionsResponse struct {
	Fields               []byte   `protobuf:"bytes,1,req,name=Fields" json:"Fields,omitempty"`
	Dimensions           []string `protobuf:"bytes,2,rep,name=Dimensions" json:"Dimensions,omitempty"`
	Err                  *string  `protobuf:"bytes,3,opt,name=Err" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FieldDimensionsResponse) Reset()         { *m = FieldDimensionsResponse{} }
func (m *FieldDimensionsResponse) String() string { return proto.CompactTextString(m) }
func (*FieldDimensionsResponse) ProtoMessage()    {}
func (*FieldDimensionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7438786364df21e1, []int{11}
}
func (m *FieldDimensionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldDimensionsResponse.Unmarshal(m, b)
}
func (m *FieldDimensionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldDimensionsResponse.Marshal(b, m, deterministic)
}
func (m *FieldDimensionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldDimensionsResponse.Merge(m, src)
}
func (m *FieldDimensionsResponse) XXX_Size() int {
	return xxx_messageInfo_FieldDimensionsResponse.Size(m)
}
func (m *FieldDimensionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldDimensionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FieldDimensionsResponse proto.InternalMessageInfo

func (m *FieldDimensionsResponse) GetFields() []byte {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *FieldDimensionsResponse) GetDimensions() []string {
	if m != nil {
		return m.Dimensions
	}
	return nil
}

func (m *FieldDimensionsResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

type MapTypeRequest struct {
	ShardIDs             []uint64 `protobuf:"varint,1,rep,name=ShardIDs" json:"ShardIDs,omitempty"`
	Measurement          []byte   `protobuf:"bytes,2,req,name=Measurement" json:"Measurement,omitempty"`
	Field                *string  `protobuf:"bytes,3,req,name=Field" json:"Field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MapTypeRequest) Reset()         { *m = MapTypeRequest{} }
func (m *MapTypeRequest) String() string { return proto.CompactTextString(m) }
func (*MapTypeRequest) ProtoMessage()    {}
func (*MapTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7438786364df21e1, []int{12}
}
func (m *MapTypeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapTypeRequest.Unmarshal(m, b)
}
func (m *MapTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapTypeRequest.Marshal(b, m, deterministic)
}
func (m *MapTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapTypeRequest.Merge(m, src)
}
func (m *MapTypeRequest) XXX_Size() int {
	return xxx_messageInfo_MapTypeRequest.Size(m)
}
func (m *MapTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MapTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MapTypeRequest proto.InternalMessageInfo

func (m *MapTypeRequest) GetShardIDs() []uint64 {
	if m != nil {
		return m.ShardIDs
	}
	return nil
}

func (m *MapTypeRequest) GetMeasurement() []byte {
	if m != nil {
		return m.Measurement
	}
	return nil
}

func (m *MapTypeRequest) GetField() string {
	if m != nil && m.Field != nil {
		return *m.Field
	}
	return ""
}

type MapTypeResponse struct {
	Type                 *int32   `protobuf:"varint,1,req,name=Type" json:"Type,omitempty"`
	Err                  *string  `protobuf:"bytes,2,opt,name=Err" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MapTypeResponse) Reset()         { *m = MapTypeResponse{} }
func (m *MapTypeResponse) String() string { return proto.CompactTextString(m) }
func (*MapTypeResponse) ProtoMessage()    {}
func (*MapTypeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7438786364df21e1, []int{13}
}
func (m *MapTypeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapTypeResponse.Unmarshal(m, b)
}
func (m *MapTypeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapTypeResponse.Marshal(b, m, deterministic)
}
func (m *MapTypeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapTypeResponse.Merge(m, src)
}
func (m *MapTypeResponse) XXX_Size() int {
	return xxx_messageInfo_MapTypeResponse.Size(m)
}
func (m *MapTypeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MapTypeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MapTypeResponse proto.InternalMessageInfo

func (m *MapTypeResponse) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *MapTypeResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

type ExpandSourcesRequest struct {
	ShardIDs             []uint64 `protobuf:"varint,1,rep,name=ShardIDs" json:"ShardIDs,omitempty"`
	Sources              []byte   `protobuf:"bytes,2,req,name=Sources" json:"Sources,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExpandSourcesRequest) Reset()         { *m = ExpandSourcesRequest{} }
func (m *ExpandSourcesRequest) String() string { return proto.CompactTextString(m) }
func (*ExpandSourcesRequest) ProtoMessage()    {}
func (*ExpandSourcesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7438786364df21e1, []int{14}
}
func (m *ExpandSourcesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExpandSourcesRequest.Unmarshal(m, b)
}
func (m *ExpandSourcesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExpandSourcesRequest.Marshal(b, m, deterministic)
}
func (m *ExpandSourcesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExpandSourcesRequest.Merge(m, src)
}
func (m *ExpandSourcesRequest) XXX_Size() int {
	return xxx_messageInfo_ExpandSourcesRequest.Size(m)
}
func (m *ExpandSourcesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExpandSourcesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExpandSourcesRequest proto.InternalMessageInfo

func (m *ExpandSourcesRequest) GetShardIDs() []uint64 {
	if m != nil {
		return m.ShardIDs
	}
	return nil
}

func (m *ExpandSourcesRequest) GetSources() []byte {
	if m != nil {
		return m.Sources
	}
	return nil
}

type ExpandSourcesResponse struct {
	Sources              []byte   `protobuf:"bytes,1,req,name=Sources" json:"Sources,omitempty"`
	Err                  *string  `protobuf:"bytes,2,opt,name=Err" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExpandSourcesResponse) Reset()         { *m = ExpandSourcesResponse{} }
func (m *ExpandSourcesResponse) String() string { return proto.CompactTextString(m) }
func (*ExpandSourcesResponse) ProtoMessage()    {}
func (*ExpandSourcesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7438786364df21e1, []int{15}
}
func (m *ExpandSourcesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExpandSourcesResponse.Unmarshal(m, b)
}
func (m *ExpandSourcesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExpandSourcesResponse.Marshal(b, m, deterministic)
}
func (m *ExpandSourcesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExpandSourcesResponse.Merge(m, src)
}
func (m *ExpandSourcesResponse) XXX_Size() int {
	return xxx_messageInfo_ExpandSourcesResponse.Size(m)
}
func (m *ExpandSourcesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExpandSourcesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExpandSourcesResponse proto.InternalMessageInfo

func (m *ExpandSourcesResponse) GetSources() []byte {
	if m != nil {
		return m.Sources
	}
	return nil
}

func (m *ExpandSourcesResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

type BackupShardRequest struct {
	ShardID              *uint64  `protobuf:"varint,1,req,name=ShardID" json:"ShardID,omitempty"`
	Since                *int64   `protobuf:"varint,2,opt,name=Since" json:"Since,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackupShardRequest) Reset()         { *m = BackupShardRequest{} }
func (m *BackupShardRequest) String() string { return proto.CompactTextString(m) }
func (*BackupShardRequest) ProtoMessage()    {}
func (*BackupShardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7438786364df21e1, []int{16}
}
func (m *BackupShardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupShardRequest.Unmarshal(m, b)
}
func (m *BackupShardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupShardRequest.Marshal(b, m, deterministic)
}
func (m *BackupShardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupShardRequest.Merge(m, src)
}
func (m *BackupShardRequest) XXX_Size() int {
	return xxx_messageInfo_BackupShardRequest.Size(m)
}
func (m *BackupShardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupShardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BackupShardRequest proto.InternalMessageInfo

func (m *BackupShardRequest) GetShardID() uint64 {
	if m != nil && m.ShardID != nil {
		return *m.ShardID
	}
	return 0
}

func (m *BackupShardRequest) GetSince() int64 {
	if m != nil && m.Since != nil {
		return *m.Since
	}
	return 0
}

type BackupShardResponse struct {
	Err                  *string  `protobuf:"bytes,1,opt,name=Err" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackupShardResponse) Reset()         { *m = BackupShardResponse{} }
func (m *BackupShardResponse) String() string { return proto.CompactTextString(m) }
func (*BackupShardResponse) ProtoMessage()    {}
func (*BackupShardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7438786364df21e1, []int{17}
}
func (m *BackupShardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupShardResponse.Unmarshal(m, b)
}
func (m *BackupShardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupShardResponse.Marshal(b, m, deterministic)
}
func (m *BackupShardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupShardResponse.Merge(m, src)
}
func (m *BackupShardResponse) XXX_Size() int {
	return xxx_messageInfo_BackupShardResponse.Size(m)
}
func (m *BackupShardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupShardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BackupShardResponse proto.InternalMessageInfo

func (m *BackupShardResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

type CopyShardRequest struct {
	Host                 *string  `protobuf:"bytes,1,req,name=Host" json:"Host,omitempty"`
	Database             *string  `protobuf:"bytes,2,req,name=Database" json:"Database,omitempty"`
	Policy               *string  `protobuf:"bytes,3,req,name=Policy" json:"Policy,omitempty"`
	ShardID              *uint64  `protobuf:"varint,4,req,name=ShardID" json:"ShardID,omitempty"`
	Since                *int64   `protobuf:"varint,5,opt,name=Since" json:"Since,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CopyShardRequest) Reset()         { *m = CopyShardRequest{} }
func (m *CopyShardRequest) String() string { return proto.CompactTextString(m) }
func (*CopyShardRequest) ProtoMessage()    {}
func (*CopyShardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7438786364df21e1, []int{18}
}
func (m *CopyShardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CopyShardRequest.Unmarshal(m, b)
}
func (m *CopyShardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CopyShardRequest.Marshal(b, m, deterministic)
}
func (m *CopyShardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CopyShardRequest.Merge(m, src)
}
func (m *CopyShardRequest) XXX_Size() int {
	return xxx_messageInfo_CopyShardRequest.Size(m)
}
func (m *CopyShardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CopyShardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CopyShardRequest proto.InternalMessageInfo

func (m *CopyShardRequest) GetHost() string {
	if m != nil && m.Host != nil {
		return *m.Host
	}
	return ""
}

func (m *CopyShardRequest) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

func (m *CopyShardRequest) GetPolicy() string {
	if m != nil && m.Policy != nil {
		return *m.Policy
	}
	return ""
}

func (m *CopyShardRequest) GetShardID() uint64 {
	if m != nil && m.ShardID != nil {
		return *m.ShardID
	}
	return 0
}

func (m *CopyShardRequest) GetSince() int64 {
	if m != nil && m.Since != nil {
		return *m.Since
	}
	return 0
}

type CopyShardResponse struct {
	Err                  *string  `protobuf:"bytes,1,opt,name=Err" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CopyShardResponse) Reset()         { *m = CopyShardResponse{} }
func (m *CopyShardResponse) String() string { return proto.CompactTextString(m) }
func (*CopyShardResponse) ProtoMessage()    {}
func (*CopyShardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7438786364df21e1, []int{19}
}
func (m *CopyShardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CopyShardResponse.Unmarshal(m, b)
}
func (m *CopyShardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CopyShardResponse.Marshal(b, m, deterministic)
}
func (m *CopyShardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CopyShardResponse.Merge(m, src)
}
func (m *CopyShardResponse) XXX_Size() int {
	return xxx_messageInfo_CopyShardResponse.Size(m)
}
func (m *CopyShardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CopyShardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CopyShardResponse proto.InternalMessageInfo

func (m *CopyShardResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

type RemoveShardRequest struct {
	ShardID              *uint64  `protobuf:"varint,1,req,name=ShardID" json:"ShardID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveShardRequest) Reset()         { *m = RemoveShardRequest{} }
func (m *RemoveShardRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveShardRequest) ProtoMessage()    {}
func (*RemoveShardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7438786364df21e1, []int{20}
}
func (m *RemoveShardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveShardRequest.Unmarshal(m, b)
}
func (m *RemoveShardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveShardRequest.Marshal(b, m, deterministic)
}
func (m *RemoveShardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveShardRequest.Merge(m, src)
}
func (m *RemoveShardRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveShardRequest.Size(m)
}
func (m *RemoveShardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveShardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveShardRequest proto.InternalMessageInfo

func (m *RemoveShardRequest) GetShardID() uint64 {
	if m != nil && m.ShardID != nil {
		return *m.ShardID
	}
	return 0
}

type RemoveShardResponse struct {
	Err                  *string  `protobuf:"bytes,1,opt,name=Err" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveShardResponse) Reset()         { *m = RemoveShardResponse{} }
func (m *RemoveShardResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveShardResponse) ProtoMessage()    {}
func (*RemoveShardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7438786364df21e1, []int{21}
}
func (m *RemoveShardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveShardResponse.Unmarshal(m, b)
}
func (m *RemoveShardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveShardResponse.Marshal(b, m, deterministic)
}
func (m *RemoveShardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveShardResponse.Merge(m, src)
}
func (m *RemoveShardResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveShardResponse.Size(m)
}
func (m *RemoveShardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveShardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveShardResponse proto.InternalMessageInfo

func (m *RemoveShardResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

type JoinClusterRequest struct {
	MetaServers          []string `protobuf:"bytes,1,rep,name=MetaServers" json:"MetaServers,omitempty"`
	Update               *bool    `protobuf:"varint,2,req,name=Update" json:"Update,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinClusterRequest) Reset()         { *m = JoinClusterRequest{} }
func (m *JoinClusterRequest) String() string { return proto.CompactTextString(m) }
func (*JoinClusterRequest) ProtoMessage()    {}
func (*JoinClusterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7438786364df21e1, []int{22}
}
func (m *JoinClusterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinClusterRequest.Unmarshal(m, b)
}
func (m *JoinClusterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinClusterRequest.Marshal(b, m, deterministic)
}
func (m *JoinClusterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinClusterRequest.Merge(m, src)
}
func (m *JoinClusterRequest) XXX_Size() int {
	return xxx_messageInfo_JoinClusterRequest.Size(m)
}
func (m *JoinClusterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinClusterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinClusterRequest proto.InternalMessageInfo

func (m *JoinClusterRequest) GetMetaServers() []string {
	if m != nil {
		return m.MetaServers
	}
	return nil
}

func (m *JoinClusterRequest) GetUpdate() bool {
	if m != nil && m.Update != nil {
		return *m.Update
	}
	return false
}

type JoinClusterResponse struct {
	Err                  *string  `protobuf:"bytes,1,opt,name=Err" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinClusterResponse) Reset()         { *m = JoinClusterResponse{} }
func (m *JoinClusterResponse) String() string { return proto.CompactTextString(m) }
func (*JoinClusterResponse) ProtoMessage()    {}
func (*JoinClusterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7438786364df21e1, []int{23}
}
func (m *JoinClusterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinClusterResponse.Unmarshal(m, b)
}
func (m *JoinClusterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinClusterResponse.Marshal(b, m, deterministic)
}
func (m *JoinClusterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinClusterResponse.Merge(m, src)
}
func (m *JoinClusterResponse) XXX_Size() int {
	return xxx_messageInfo_JoinClusterResponse.Size(m)
}
func (m *JoinClusterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinClusterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinClusterResponse proto.InternalMessageInfo

func (m *JoinClusterResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

type LeaveClusterResponse struct {
	Err                  *string  `protobuf:"bytes,1,opt,name=Err" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveClusterResponse) Reset()         { *m = LeaveClusterResponse{} }
func (m *LeaveClusterResponse) String() string { return proto.CompactTextString(m) }
func (*LeaveClusterResponse) ProtoMessage()    {}
func (*LeaveClusterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7438786364df21e1, []int{24}
}
func (m *LeaveClusterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveClusterResponse.Unmarshal(m, b)
}
func (m *LeaveClusterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveClusterResponse.Marshal(b, m, deterministic)
}
func (m *LeaveClusterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveClusterResponse.Merge(m, src)
}
func (m *LeaveClusterResponse) XXX_Size() int {
	return xxx_messageInfo_LeaveClusterResponse.Size(m)
}
func (m *LeaveClusterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveClusterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveClusterResponse proto.InternalMessageInfo

func (m *LeaveClusterResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*WriteShardRequest)(nil), "internal.WriteShardRequest")
	proto.RegisterType((*WriteShardResponse)(nil), "internal.WriteShardResponse")
	proto.RegisterType((*ExecuteStatementRequest)(nil), "internal.ExecuteStatementRequest")
	proto.RegisterType((*ExecuteStatementResponse)(nil), "internal.ExecuteStatementResponse")
	proto.RegisterType((*CreateIteratorRequest)(nil), "internal.CreateIteratorRequest")
	proto.RegisterType((*CreateIteratorResponse)(nil), "internal.CreateIteratorResponse")
	proto.RegisterType((*IteratorStats)(nil), "internal.IteratorStats")
	proto.RegisterType((*IteratorCostRequest)(nil), "internal.IteratorCostRequest")
	proto.RegisterType((*IteratorCostResponse)(nil), "internal.IteratorCostResponse")
	proto.RegisterType((*IteratorCost)(nil), "internal.IteratorCost")
	proto.RegisterType((*FieldDimensionsRequest)(nil), "internal.FieldDimensionsRequest")
	proto.RegisterType((*FieldDimensionsResponse)(nil), "internal.FieldDimensionsResponse")
	proto.RegisterType((*MapTypeRequest)(nil), "internal.MapTypeRequest")
	proto.RegisterType((*MapTypeResponse)(nil), "internal.MapTypeResponse")
	proto.RegisterType((*ExpandSourcesRequest)(nil), "internal.ExpandSourcesRequest")
	proto.RegisterType((*ExpandSourcesResponse)(nil), "internal.ExpandSourcesResponse")
	proto.RegisterType((*BackupShardRequest)(nil), "internal.BackupShardRequest")
	proto.RegisterType((*BackupShardResponse)(nil), "internal.BackupShardResponse")
	proto.RegisterType((*CopyShardRequest)(nil), "internal.CopyShardRequest")
	proto.RegisterType((*CopyShardResponse)(nil), "internal.CopyShardResponse")
	proto.RegisterType((*RemoveShardRequest)(nil), "internal.RemoveShardRequest")
	proto.RegisterType((*RemoveShardResponse)(nil), "internal.RemoveShardResponse")
	proto.RegisterType((*JoinClusterRequest)(nil), "internal.JoinClusterRequest")
	proto.RegisterType((*JoinClusterResponse)(nil), "internal.JoinClusterResponse")
	proto.RegisterType((*LeaveClusterResponse)(nil), "internal.LeaveClusterResponse")
}

func init() { proto.RegisterFile("internal/data.proto", fileDescriptor_7438786364df21e1) }

var fileDescriptor_7438786364df21e1 = []byte{
	// 748 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x6d, 0x4f, 0xdb, 0x48,
	0x10, 0x96, 0xe3, 0x84, 0x4b, 0x86, 0xdc, 0x01, 0x4b, 0x08, 0x16, 0x3a, 0x9d, 0xa2, 0x95, 0x4e,
	0x17, 0x9d, 0xd4, 0x54, 0xe2, 0x4b, 0x3f, 0x97, 0x04, 0x04, 0x15, 0xa4, 0x68, 0x43, 0xe9, 0xe7,
	0xad, 0x3d, 0x02, 0x8b, 0xc4, 0xeb, 0x7a, 0xd7, 0x08, 0xfa, 0x13, 0xda, 0x3f, 0xd6, 0x9f, 0x55,
	0xed, 0xf8, 0x25, 0x36, 0x34, 0x2d, 0xaa, 0xe8, 0xb7, 0x7d, 0x9e, 0x1d, 0xcf, 0x3c, 0xf3, 0xb6,
	0x86, 0xed, 0x30, 0x32, 0x98, 0x44, 0x72, 0xfe, 0x32, 0x90, 0x46, 0x8e, 0xe2, 0x44, 0x19, 0xc5,
	0xda, 0x05, 0xc9, 0xbf, 0x38, 0xb0, 0xf5, 0x3e, 0x09, 0x0d, 0xce, 0xae, 0x65, 0x12, 0x08, 0xfc,
	0x98, 0xa2, 0x36, 0xcc, 0x83, 0x3f, 0x08, 0x9f, 0x4c, 0x3c, 0x67, 0xd0, 0x18, 0x36, 0x45, 0x01,
	0x59, 0x1f, 0xd6, 0xce, 0x55, 0x18, 0x19, 0xed, 0x35, 0x06, 0xee, 0xb0, 0x2b, 0x72, 0xc4, 0xf6,
	0xa0, 0x3d, 0x91, 0x46, 0x7e, 0x90, 0x1a, 0x3d, 0x77, 0xe0, 0x0c, 0x3b, 0xa2, 0xc4, 0x6c, 0x08,
	0x1b, 0x02, 0x0d, 0x46, 0x26, 0x54, 0xd1, 0xb9, 0x9a, 0x87, 0xfe, 0xbd, 0xd7, 0x24, 0x93, 0x87,
	0x34, 0x3f, 0x00, 0x56, 0x15, 0xa3, 0x63, 0x15, 0x69, 0x64, 0x0c, 0x9a, 0x63, 0x15, 0x20, 0x49,
	0x69, 0x09, 0x3a, 0x5b, 0x85, 0x67, 0xa8, 0xb5, 0xbc, 0x42, 0xaf, 0x41, 0xbe, 0x0a, 0xc8, 0x67,
	0xb0, 0x7b, 0x78, 0x87, 0x7e, 0x6a, 0x70, 0x66, 0xa4, 0xc1, 0x05, 0x46, 0xa6, 0x48, 0xeb, 0x6f,
	0xe8, 0x94, 0x1c, 0x79, 0xeb, 0x88, 0x25, 0x51, 0x4b, 0xa1, 0x41, 0x97, 0x25, 0xe6, 0xc7, 0xe0,
	0x3d, 0x76, 0xfa, 0x4b, 0xf2, 0xae, 0x60, 0x67, 0x9c, 0xa0, 0x34, 0x78, 0x62, 0x30, 0x91, 0x46,
	0x25, 0x85, 0xb8, 0x3d, 0x68, 0xe7, 0x45, 0xd6, 0x9e, 0x33, 0x70, 0x87, 0x4d, 0x51, 0x62, 0x36,
	0x80, 0xf5, 0x33, 0x94, 0x3a, 0x4d, 0x32, 0xe9, 0x56, 0x5d, 0x57, 0x54, 0x29, 0xb6, 0x09, 0xee,
	0xdb, 0xd8, 0x78, 0x2e, 0xdd, 0xd8, 0x23, 0x5f, 0x40, 0xff, 0x61, 0xa0, 0x5c, 0xf0, 0x26, 0xb8,
	0x87, 0x49, 0xe2, 0x39, 0x24, 0xcc, 0x1e, 0x6d, 0x0a, 0x17, 0xf7, 0x71, 0x96, 0x76, 0x4b, 0xd0,
	0x99, 0xbd, 0x80, 0x96, 0xcd, 0x55, 0x53, 0x3b, 0xd7, 0xf7, 0x77, 0x47, 0xc5, 0xcc, 0x8c, 0x0a,
	0x87, 0x74, 0x2d, 0x32, 0x2b, 0xfe, 0x1a, 0xfe, 0xac, 0xf1, 0x34, 0x43, 0x98, 0x84, 0xa8, 0xa7,
	0x14, 0xc9, 0x15, 0x05, 0x2c, 0x67, 0x68, 0x4a, 0xb5, 0x71, 0xf3, 0x19, 0x9a, 0x72, 0x84, 0xed,
	0xc2, 0xc5, 0x58, 0x69, 0xf3, 0xbb, 0x0a, 0x73, 0x01, 0xbd, 0x7a, 0x98, 0x95, 0x65, 0xf9, 0xdf,
	0x76, 0x56, 0x1b, 0x92, 0xb9, 0xbe, 0xdf, 0x7f, 0x5c, 0x01, 0xfa, 0x9e, 0x6c, 0xf8, 0x57, 0x07,
	0xba, 0x55, 0xda, 0x0e, 0xdb, 0x34, 0x5d, 0x90, 0x52, 0x9d, 0x57, 0x60, 0x49, 0x14, 0xb7, 0x54,
	0x91, 0xbc, 0x0c, 0x4b, 0x82, 0x71, 0xe8, 0x8e, 0xa5, 0x7f, 0x8d, 0xc1, 0xa5, 0x9c, 0xa7, 0x98,
	0xb5, 0xc0, 0x15, 0x35, 0xce, 0x96, 0x65, 0x9a, 0x2e, 0x8e, 0xc2, 0x39, 0x6a, 0x5a, 0x27, 0x57,
	0x94, 0x98, 0xfd, 0x03, 0x70, 0x30, 0x57, 0xfe, 0x8d, 0x16, 0x28, 0x03, 0xaf, 0x45, 0xb7, 0x15,
	0xc6, 0x46, 0x27, 0x34, 0x0b, 0x3f, 0xa1, 0xb7, 0x96, 0x45, 0x2f, 0x09, 0x7e, 0x09, 0xfd, 0xa3,
	0x10, 0xe7, 0xc1, 0x24, 0x5c, 0x60, 0xa4, 0x43, 0x15, 0xe9, 0x67, 0x69, 0x05, 0xf7, 0x61, 0xf7,
	0x91, 0xdf, 0xbc, 0xf6, 0x7d, 0x58, 0xa3, 0x2b, 0x4d, 0x5b, 0xd4, 0x15, 0x39, 0xb2, 0x89, 0x2c,
	0xad, 0xe9, 0xc9, 0xe9, 0x88, 0x0a, 0x53, 0xf4, 0xcc, 0x2d, 0x7b, 0xc6, 0x03, 0xf8, 0xeb, 0x4c,
	0xc6, 0x76, 0x82, 0x9f, 0x67, 0x7e, 0x7a, 0xd0, 0x22, 0x2d, 0x34, 0x41, 0x1d, 0x91, 0x01, 0xfe,
	0x0a, 0x36, 0xca, 0x28, 0xcb, 0x67, 0x80, 0x76, 0xc8, 0xa9, 0xec, 0x50, 0x2e, 0xaf, 0xb1, 0x94,
	0x77, 0x0a, 0xbd, 0xc3, 0xbb, 0x58, 0x46, 0xc1, 0x4c, 0xa5, 0x89, 0x8f, 0x4f, 0xaa, 0xac, 0xdd,
	0xa4, 0xcc, 0x3a, 0x17, 0x58, 0x40, 0x3e, 0x86, 0x9d, 0x07, 0xde, 0x72, 0x31, 0x95, 0x4f, 0x9c,
	0xda, 0x27, 0xdf, 0x91, 0x34, 0x01, 0x76, 0x20, 0xfd, 0x9b, 0x34, 0x7e, 0xe2, 0x2f, 0xa0, 0x07,
	0xad, 0x59, 0x18, 0xf9, 0x98, 0x8f, 0x6d, 0x06, 0xf8, 0x7f, 0xb0, 0x5d, 0xf3, 0xb2, 0x6a, 0xa9,
	0xf8, 0x67, 0x07, 0x36, 0xc7, 0x2a, 0xbe, 0xaf, 0x45, 0x63, 0xd0, 0x3c, 0xb6, 0x9b, 0x96, 0x3d,
	0xca, 0x74, 0xfe, 0xd1, 0x7b, 0x9c, 0x3d, 0x21, 0xf4, 0x27, 0xc9, 0xda, 0x92, 0xa3, 0xaa, 0xea,
	0xe6, 0x0a, 0xd5, 0xad, 0xaa, 0xea, 0x7f, 0x61, 0xab, 0xa2, 0x65, 0xa5, 0xe6, 0x11, 0x30, 0x81,
	0x0b, 0x75, 0xfb, 0xc4, 0xbf, 0xa4, 0x2d, 0x46, 0xcd, 0x7e, 0xa5, 0xe3, 0x29, 0xb0, 0x37, 0x2a,
	0x8c, 0xc6, 0xf3, 0x54, 0x1b, 0x2c, 0x7f, 0x05, 0x34, 0x95, 0x46, 0xce, 0x30, 0xb9, 0xc5, 0x24,
	0x9b, 0x87, 0x8e, 0xa8, 0x52, 0x36, 0xff, 0x77, 0x71, 0x20, 0x4d, 0x56, 0x99, 0xb6, 0xc8, 0x91,
	0x0d, 0x5c, 0xf3, 0xb7, 0x32, 0xf0, 0x10, 0x7a, 0xa7, 0x28, 0x6f, 0xf1, 0xa7, 0x96, 0xdf, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x85, 0x71, 0x41, 0x34, 0x41, 0x08, 0x00, 0x00,
}
